home_pizza_index:
    pattern : /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

customize_pizza:
    pattern: /customize/{id}
    defaults: { _controller: "AppBundle:Default:customize" }
    methods: [GET,POST]

view_pizza:
    pattern: /view/{id}
    defaults: { _controller: "AppBundle:Default:view" }