pizza_index:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Pizza:index" }
    methods:  GET

pizza_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Pizza:show" }
    methods:  GET

pizza_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Pizza:new" }
    methods:  [GET, POST]

pizza_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Pizza:edit" }
    methods:  [GET, POST]

pizza_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Pizza:delete" }
    methods:  DELETE

pizza_price:
    path: /getPizzaPrice
    defaults: { _controller: "AppBundle:Admin/Pizza:getPizzaPrice" }
    methods: GET